version: "3.8"
services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data

  web: &web
    build: .
    image: app:1.0.0
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
      - rails_cache:/app/tmp/cache
    tmpfs:
      - /tmp
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose: ["3000"]
    ports: ["3000:3000"]
    command: /bin/sh -c "bin/rails server -b 0.0.0.0"
    user: root
    working_dir: /app

  worker:
    <<: *web
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec sidekiq"
    expose: ["6379"]
    ports: ["6379:6379"]

volumes:
  postgres:
  redis:
  bundle:
  rails_cache:
