source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

gem 'rails', '~> 6.1.4'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 5.0'
gem 'bcrypt', '~> 3.1.13'
gem 'image_processing', '~> 1.2'

gem 'active_model_serializers', '~> 0.10.0'
gem 'alba'
gem 'simple_command'
gem 'active_interaction', '~> 4.0'

gem 'aws-sdk-s3', '~> 1'
gem "letter_opener"
gem 'letter_opener_web', '~> 1.0'
gem 'bootsnap', '>= 1.4.4', require: false

gem 'rack-cors'

group :development, :test do
  gem 'bullet'
  gem 'faker'
  gem 'factory_bot'
  gem 'rspec-rails', '~> 5.0.0'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'byebug'
end

group :development do
  gem 'annotate'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-byebug'
end
