source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.3'

gem 'rails', '~> 7.1.3'
gem 'pg'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1.20'
gem 'image_processing', '~> 1.2'

gem 'active_model_serializers', '~> 0.10.0'
gem 'simple_command'
gem 'active_interaction', '~> 4.0'
gem 'graphql'
gem 'search_object_graphql'

gem 'aws-sdk-s3', '~> 1'
gem "letter_opener"
gem 'letter_opener_web', '~> 1.0'
gem 'bootsnap', require: false

gem 'sidekiq'

gem 'rack-cors'

group :development, :test do
  gem 'bullet'
  gem 'factory_bot'
  gem 'faker'
  gem 'rspec-rails', '~> 6.1.0'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'byebug'
end

group :development do
  gem 'annotate'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'graphiql-rails'
  gem 'sprockets', '~> 3.7.2'
  gem 'solargraph'
end
