import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [loading, setLoading] = useState(true)
  const [questions, setQuestions] = useState<{id: string; title: string}[]>([])

  useEffect(() => {
    if (process.env.NODE_ENV === 'development') {
      const { worker } = require('../mocks/browsers')
      worker.start()
    }
    async function fetchData() {
      const response = await axios.get<{id: string; title: string}[]>('/novels');
      return response
    }

    fetchData()
      .then(res => {
        setQuestions(res.data);
      })
      .catch(e => {
        alert(e);
      })
      .finally(() => {
        setLoading(false)
      })
  }, [loading]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {questions.map(item => (
          <li key={item.id}>
            <Link
              href={{
                pathname: '/questions/[slug]',
                query: { slug: item.id },
              }}
            >
              <a>{item.title}</a>
            </Link>
          </li>
        ))}
      </main>
    </div>
  )
}

export default Home
