import { NextPage } from "next"
import Head from 'next/head'
import { NavigationHeader } from '../../components/layouts/NavigationHeader'

const QuestionIndex: NextPage = () => {
  return (
    <>
      <Head>
        <title>PHPフォルダから複数のファイルを取得し、ファイルを一つずつ読み込む方法</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationHeader />
      
      <main>
        <div className="py-4 bg-gray-100">
          <div className="flex max-w-4xl mx-auto">
            <div className="w-2/3 bg-white p-4 mr-8">
              <p className="text-xl font-bold">
                PHPフォルダから複数のファイルを取得し、ファイルを一つずつ読み込む方法
              </p>
            </div>
            <div className="w-1/3 bg-blue-100">w-1/3</div>
          </div>
        </div>
      </main>
    </>
  )
}

export default QuestionIndex;
