import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavigationHeader } from "@/components/NavigationHeader";
import { Sidebar } from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-9 gap-4 p-4 bg-gray-50 min-h-dvh">
      <Sidebar />
      {children}
    </div>
  );
}
