import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  question,
  pokemon,
}: Readonly<{
  children: React.ReactNode;
  question: React.ReactNode;
  pokemon: React.ReactNode;
}>) {
  return (
    <div className="col-span-7">
      {children}
      {pokemon}
      {question}
    </div>
  );
}
